### ISSUE TITLE
Not compatible with node.js 0.6.x ?

### ISSUE THREAD

**Issue by oppih** [mrcoles/cssunminifier#1]
It came with cssunminifier:

```
The "sys" module is now called "util". It should have a similar interface.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
```

I searched on this problem and it someone said it is caused since the script is not compatible with node.js 0.6.x .

Anyone can fix it?

**Comment by mrcoles** [comment]
You’re quite right. Some stuff has changed in node since I released this. I just updated the project and successfully unminified some CSS with v0.6.8.
